# Generated by Django 4.2.16 on 2024-11-24 02:45

from django.db import migrations, models
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='https://res.cloudinary.com/dulfdtcut/image/upload/v1729505935/cld-sample-4.jpg', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
