# Generated by Django 4.2.16 on 2024-11-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image_post_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='Post article image', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post-article-slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
