# Generated by Django 4.2.16 on 2024-11-24 12:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image_alt_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='https://res.cloudinary.com/dulfdtcut/image/upload/v1731383533/recipes/Screenshot_2024-10-25_211028_zlqtk7.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_alt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
