# Generated by Django 4.2.16 on 2024-11-26 22:59

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postcomment_options_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='https://res.cloudinary.com/dulfdtcut/image/upload/v1732624989/posts/oils_byapkh.webp', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
