# Generated by Django 4.2.16 on 2024-12-01 07:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='CLOUDINARY', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='posts/'),
        ),
    ]
