# Generated by Django 4.2.16 on 2024-11-01 20:12

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('ingredients', models.TextField(default='Ingredients', max_length=10000)),
                ('instructions', models.TextField(default='Instructions', max_length=10000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='recipes/')),
                ('image_alt', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('lowsugar', models.BooleanField()),
                ('glutenfree', models.BooleanField()),
                ('dairyfree', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('vegitarian', models.BooleanField()),
                ('highfiber', models.BooleanField()),
                ('highprotein', models.BooleanField()),
                ('nutfree', models.BooleanField()),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
