# Generated by Django 4.2.16 on 2024-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dairyfree',
            field=models.BooleanField(default=False, help_text='Dairyfree,        e.g. Milk, Yogurt, Cheese, lactose-free milk'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='glutenfree',
            field=models.BooleanField(default=False, help_text='e.g. Wheat,        Varieties and derivatives of wheat such as: Rye, Barley, Triticale.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='highfiber',
            field=models.BooleanField(default=False, help_text='High-Fiber Food,        e.g. Avocado, Artichoke, Lentils, Apple, Beans, Chickpea etc..'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='highprotein',
            field=models.BooleanField(default=False, help_text='e.g. Fish,        Seafood, White-meat poultry, Lean beef, Dairy, Eggs, Nuts etc..'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='lowsugar',
            field=models.BooleanField(default=False, help_text='e.g. sucrose, glucose, fructose, maltose,        fruit juice, molasses, hydrolysed starch, invert sugar, corn syrup,        honey etc.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutfree',
            field=models.BooleanField(default=False, help_text='nutfree'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False, help_text='Vegan,        no animal meat, no exception'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='vegitarian',
            field=models.BooleanField(default=False, help_text='Pescatarian,        Vegitarian, no animal meat except sea-food, eggs and dairy'),
        ),
    ]
