# Generated by Django 4.2.16 on 2024-11-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_dairyfree_alter_recipe_glutenfree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutfree',
            field=models.BooleanField(default=False, help_text='All kind of Nuts.        Not include seeds: sesame, sunflower pumpkin, macadamia nut, pine nut'),
        ),
    ]
