# Generated by Django 4.2.16 on 2024-11-15 18:41

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_cook_time_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='https://res.cloudinary.com/dulfdtcut/image/upload/v1/recipes/recipe-image-placeholder_upjwg0', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(),
        ),
    ]
